### ISSUE TITLE
AuthController /authenticate

### ISSUE THREAD

**Issue by sohskd** [ralscha/springsecuritytotp#1]
In the AuthController, there is an endpoint /authenticate.

In line 43,

when securityContextHolder.getContext.getAuthentication is not an instance of AppUserAuthentication, the httpSession expires.

In line 47,

AppUserAuthentication userAuthentication = (AppUserAuthentication) httpSession
        .getAttribute(USER_AUTHENTICATION_OBJECT);

when the session expire, userAuthentication is always null. It will never enter the  "if (userAuthentication != null)"

Please let me know in what situation would the code enter the "if (userAuthentication != null)" block.

Thank you

**Comment by ralscha** [comment]
The [code inside the if](https://github.com/ralscha/springsecuritytotp/blob/master/server/src/main/java/ch/rasc/twofa/security/AuthController.java#L49-L57) is called when you do a browser refresh after the username/password login. You need to test it with an user that has 2FA enabled.

**Comment by ralscha** [comment]
Not sure what you mean by "when securityContextHolder.getContext.getAuthentication is not an instance of AppUserAuthentication, the httpSession expires." 

`securityContextHolder.getContext.getAuthentication` could also be `null`. I guess it is `null` most of the time because this endpoint is called when the application starts up and the application uses session cookies. So everytime you open the browser and open the application, it is `null`. And it's only non-null if you hit refresh in your browser.

I guess we could change the if statement to
```if (auth != null) {```

`instanceof` does the same, it also checks for `null`
```if (auth instanceof AppUserAuthentication) {```
But I guess in our application `Authentication` is always an instance of `AppUserAuthentication` so the check if it's non-null should suffice.

**Comment by sohskd** [comment]
Hi Ralscha,

Thank you for the explanation.

May I know what is the use of 

httpSession.setAttribute(USER_AUTHENTICATION_OBJECT, userAuthentication); in line 77 of signin?

We can just use auth in line 42?

Thank you

**Comment by ralscha** [comment]
You could. But then you have to send a second HTTP request to the server. 
I wanted to handle the sign in process in one request

The problem is that there is duplicate code. I guess what we could do is removing 
lines 47 - 57: https://github.com/ralscha/springsecuritytotp/blob/master/server/src/main/java/ch/rasc/twofa/security/AuthController.java#L47-L57

"refresh-after-login" is an edge case and we could simply ignore it. If somebody clicks refresh after the login he automatically sees the login prompt again.
